site_name: example-site-name
site_url: https://organisationname.github.io/reponame

theme:
  name: material

plugins:
- search  
- git-authors
- git-revision-date-localized

# Blogging
- blogging:
    dirs: # The directories to be included
      - blog

# Auto Documentation From Code      
- gen-files: # Generate distinct docs pages per source code file.
    scripts:
    - scripts/mkdocs/gen_ref_pages.py  
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings: # Generate documentation from source code.
    default_handler: python
    handlers:
      python:
        options:
          docstring_style: google
          docstring_section_style: list
          show_if_no_docstring: true
          show_submodules: true
          show_bases: true
          
          show_root_full_path: true
          show_object_full_path: false
          group_by_category: true
          show_category_heading: true
          show_source: false
          show_signature: true
          separate_signature: true
          show_signature_annotations: true

# Swagger OpenAPI doc generation
- render_swagger

# Science and Engineering
- plotly
# - drawio-exporter
- mkdocs-jupyter

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
# nav:
# - 'index.md'
# - plotly.md
# - notebooks.md
# - Code Reference: reference/  